from __future__ import annotations

from typing import Any, Tuple

import numpy as np
from numpy.typing import NDArray


class Progress:
    def reset(self, total: int) -> None: ...
    def request_cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def done(self) -> int: ...
    def total(self) -> int: ...
    def stage(self) -> str: ...
    def planes_found(self) -> int: ...
    def active_points_remaining(self) -> int: ...
    def current_best_support(self) -> int: ...


def segment_planes(
    coords: NDArray[np.float32],
    normals: NDArray[np.float32] | None = ...,
    *,
    normal_mode: str = ...,
    params: dict[str, Any] = ...,
    progress: Progress | None = ...,
) -> Tuple[NDArray[np.int32], dict[str, Any]]: ...
