from __future__ import annotations

from typing import Any

import numpy as np
from numpy.typing import NDArray


class Progress:
    def __init__(self) -> None: ...
    def reset(self, total: int) -> None: ...
    def request_cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def done(self) -> int: ...
    def total(self) -> int: ...
    def stage(self) -> str: ...


def merge_planar_regions(
    coords: NDArray[np.float32],
    labels: NDArray[np.int32],
    params: dict[str, Any] = ...,
    progress: Progress | None = ...,
) -> tuple[NDArray[np.int32], dict[str, Any]]: ...
