from typing import Any
import numpy as np
from numpy.typing import NDArray

class Progress:
    def __init__(self) -> None: ...
    def request_cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def done(self) -> int: ...
    def total(self) -> int: ...
    def stage(self) -> str: ...

def split_between(
    coords: NDArray[np.float32],
    working_indices: NDArray[np.int64],
    a_indices: NDArray[np.int64],
    b_indices: NDArray[np.int64],
    condition: str,
    progress: Progress | None = ...,
) -> tuple[NDArray[np.uint8], dict[str, Any]]: ...
